from datetime import date

# === Date for the output plots ===
today = date.today().strftime("%Y-%m-%d")
print("\nToday's date:", today)

# === Directories ===
project_dir = "/staging/leuven/stg_00092/IBP_PRSproject/data/"

# === Prefix of the files  ===
target_files_name = "final_IBP"


rule all:
	input:
		all_score = expand(project_dir + "002_prsice_results/{name}.all_score", name=target_files_name),
		barplot = expand(project_dir + "002_prsice_results/{name}_BARPLOT_" + today + ".png", name=target_files_name),
		best = expand(project_dir + "002_prsice_results/{name}.best", name=target_files_name),
		high_res_plot = expand(project_dir + "002_prsice_results/{name}_HIGH-RES_PLOT_" + today + ".png", name=target_files_name),
		log = expand(project_dir + "002_prsice_results/{name}.log", name=target_files_name),
		mismatch = expand(project_dir + "002_prsice_results/{name}.mismatch", name=target_files_name),
		prsice = expand(project_dir + "002_prsice_results/{name}.prsice", name=target_files_name),
		quantiles_text = expand(project_dir + "002_prsice_results/{name}_QUANTILES_" + today + ".txt", name=target_files_name),
		quantiles_plot = expand(project_dir + "002_prsice_results/{name}_QUANTILES_PLOT_" + today + ".png", name=target_files_name),
		summary = expand(project_dir + "002_prsice_results/{name}.summary", name=target_files_name),

	shell:
		'''
		echo "SNAKEMAKE FILE FINISHED!!!"
		'''


rule prsice:
	input:
		base = project_dir + "IBD_basefile_hg38_PRS.txt",
		target_fam = project_dir + "{name}.fam",
		target_bed = project_dir + "{name}.bed",
		target_bim = project_dir + "{name}.bim",

		phenotype = project_dir + "final_phenotypes.txt",

	params:
		target_prefix = "{name}",
		output_prefix = project_dir + "002_prsice_results/{name}"

	output:
		barplot = project_dir + "002_prsice_results/{name}_BARPLOT_" + today + ".png",
		high_res_plot = project_dir + "002_prsice_results/{name}_HIGH-RES_PLOT_" + today + ".png",

		prsice = project_dir + "002_prsice_results/{name}.prsice",
		summary = project_dir + "002_prsice_results/{name}.summary",
		best = project_dir + "002_prsice_results/{name}.best",

		log = project_dir + "002_prsice_results/{name}.log",
		
		all_score = project_dir + "002_prsice_results/{name}.all_score",
		
		quantiles_plot = project_dir + "002_prsice_results/{name}_QUANTILES_PLOT_" + today + ".png",
		quantiles_text = project_dir + "002_prsice_results/{name}_QUANTILES_" + today + ".txt",

		mismatch = project_dir + "002_prsice_results/{name}.mismatch",

		# all_prs -> If --all-score is indicated
		# quantiles_* -> If --quantile [number of quantile] is indicated
		
	shell:
		'''
		Rscript PRSice/PRSice.R \
		    --prsice PRSice/PRSice_linux \
		    --base {input.base} \
		    --snp SNP \
			--chr CHR \
			--bp BP \
			--A1 Allele2 \
			--A2 Allele1 \
			--stat Effect \
			--pvalue P.value \
			--or \
		    --target {params.target_prefix} \
		    --binary-target F \
	 	    --pheno {input.phenotype} \
	 	    --ignore-fid \
		    --base-maf MAF:0.01 \
		    --base-info INFO:0.8 \
		    --all-score \
		    --quantile 10 \
		    --quant-ref 3 \
		    --out {params.output_prefix}
		'''

# ----------------------------------------------------------------------------------------------------
# PART 3
# . Compare the four tools
# . R plots
# . 
# . 
# ----------------------------------------------------------------------------------------------------

# --cov {input.covariates} \

# rule covariates:
# 	input:
# 		cov = project_dir + "{name}.cov",
# 		eigenvec = project_dir + "{name}.eigenvec",
# 		eigenval = project_dir + "{name}.eigenval",
# 	output:
# 		covariates = project_dir + "{name}.covariate",
# 	shell:
# 		'''
# 		Rscript PRSice/covariates.R
# 		'''


# 		covariates = project_dir + "{name}.covariate",






